version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8001"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - llm_db

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  llm_db:
    image: postgres:17
    container_name: llm_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: llm_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
